### ISSUE TITLE
Bug: `all-the-icons--icon-info-for-buffer` does not return an icon if the buffer has no associated file.

### ISSUE THREAD

**Issue by FrancisMurillo** [domtronn/all-the-icons.el#15] opened 2016-09-20 08:22 UTC
First of, great package dood. I was finally able to make my own mode line configuration inspired by this package. One of the things I always wanted to customize for a long time. Really thanks.

Anyway, let's say I have a buffer `meow.org`; the function `all-the-icons--icon-info-for-buffer` (which is called by `all-the-icons-icon-for-buffer`) returns `org-mode`. When I save the buffer as `~/meow.org`, it now returns the `icon` of org-mode which is what I wanted in the first place. Is this an intended behavior or a bug? If it is a bug, I can make a PR if I can help.

**Comment by nlamirault** [comment] 2016-09-20 09:01
Same behavior with *web-mode*.

**Comment by domtronn** [comment] 2016-09-20 15:31
Hi there, this is _somewhat_ by design. Since a lot of anonymous buffers _(like `*scratch*` etc.)_ never have files associated with them, the `all-the-icons--icon-info-for-buffer` function prioritises using the _mode_ to decide the icon instead of the file name.

When associating the major mode it uses `all-the-icons-mode-icon-alist` to pick the icon! I'll admit that this list is somewhat lacking compared to the file matcher 😅 So I would happily accept PRs to add matchers for major modes!

**Comment by nlamirault** [comment] 2016-09-20 16:27
See #16 for IELM icon.

**Comment by domtronn** [comment] 2016-09-20 17:32
@FrancisMurillo I've just pushed a matcher for anonymous `org-mode` buffers.
@nlamirault I've added a custom matcher for anonymous `web-mode` buffers which uses the `web-mode-content-type` to decide what icon is appropriate.

**Comment by nlamirault** [comment] 2016-09-20 17:46
@domtronn Great ! i will try that

**Comment by domtronn** [comment] 2016-09-27 07:39
I'm going to close this now - I'm _pretty sure_ I've addressed everything in here 😅 and I'm going to assume that you're happy now @FrancisMurillo!

**Closed by domtronn** 2016-09-27 07:39 UTC
Labels: new mode match
